PATCH http://localhost:3000/posts/
Content-Type:application/json

{
    "id":1234,
    "title":"What's new with nest js",
    "postType":"post",
    "slug":"new-with-nestjs",
    "status":"draft",
    "content":"test content",
    "schema":"{fklsdajflkdjflkfjaj}",
    "featuredImageUrl":"http://localhost.com/images/image1.jpg",
    "tags":["nestJs","typescript"],
    "metaOptions":[
        {
            "key":"testKey",
            "value":20
        }
    ]
}